from app.prompts.templates import (
    EMAIL_CLASSIFICATION_PROMPT,
    EXTRACTION_PROMPT,
    QUOTATION_EMAIL_TEMPLATE,
)

__all__ = [
    "EMAIL_CLASSIFICATION_PROMPT",
    "EXTRACTION_PROMPT",
    "QUOTATION_EMAIL_TEMPLATE",
]
